library(data.table)
library(tidyverse)
library(scales)
library(lubridate)
library(ggmap)
library(ggplot2)
library(ggtern)
lat <- c(40.675, 40.775)
long <- c(-74.02, -73.94)
bbox <- make_bbox(long,lat)
map <- get_map(bbox,maptype="toner-lite",source="stamen")
density.2d.2014 <- read.csv("dane/density_2d_2014.csv", header=TRUE)
density.2d.2018 <- read.csv("dane/density_2d_2018.csv", header=TRUE)
